name: Publish Insider Build

on:
  # only run when a comment is created under a pr
  issue_comment:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check if user is AriaMinaei and comment contains "/Publish insiders build"
        if: "${{ github.event.comment.user.login }} == 'AriaMinaei' && contains(${{ github.event.comment.body }}, '/Publish insiders build')"
        run: |
          echo "User is AriaMinaei and comment contains the trigger."

      - uses: actions/checkout@v2
      - name: Get the latest commit hash
        id: last-commit
        run: |
          COMMIT=$(git log --pretty=format:'%h' -n 1)
          echo "Latest commit hash: $COMMIT"
          echo "last-commit=$COMMIT" >> $GITHUB_ENV

      - name: Respond with the latest commit hash
        uses: actions/github-script@v3
        with:
          github-token: "${{ env.GITHUB_TOKEN }}"
          script: |
            const commentBody = `Okay, i'll publish ${{env.last-commit}}`;
            const { data: { id: commentId } } = await octokit.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody
            });
