name: Publish Insider Build

on:
  # only run when a comment is created under a pr
  issue_comment:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    permissions:
      issues: write
      # allow writing comments on the PR
      contents: write
      pull-requests: write

    steps:
      - name: Start the comment
        id: start-comment
        uses: actions/github-script@v6
        with:
          encoding: string
          script: |
            const result = await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              Publishing an insiders build. Will update this comment when done.
              <details><summary>see more</summary>

              Follow the workflow run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

              </details>
              `
            })

            console.log(result)

            const commentId = result.data.id

            return commentId

      - name: Get the pull request's ref
        id: pr-ref
        uses: actions/github-script@v6
        with:
          script: |
            const {data: pullRequest} = await github.rest.pulls.get({
              ...context.repo,
              pull_number: context.issue.number
            })

            console.log(pullRequest)

            return {ref: pullRequest.head.ref, sha: pullRequest.head.sha}

      - name: Check if user is AriaMinaei and comment contains "/Publish insiders build"
        if: "${{ github.event.comment.user.login }} == 'AriaMinaei' && contains(${{ github.event.comment.body }}, '/Publish insiders build')"
        run: |
          echo "User is AriaMinaei and comment contains the trigger."

      - name: print the ref
        run: |
          echo "toJSON( ${{ steps.pr-ref.outputs.result }} )"

      # checkout the repo at the latest commit of the PR
      - uses: actions/checkout@v2
        with:
          ref: ${{ fromJSON( steps.pr-ref.outputs.result.sha ) }}

      - name: Update the comment
        id: update-comment
        uses: actions/github-script@v6
        with:
          script: |
            console.log(${{ toJSON(steps.pr-ref.outputs.result) }})

            const result = await github.rest.issues.updateComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: "${{ steps.start-comment.outputs.result }}",
              body: `
              Published at commit ${{ steps.pr-ref.outputs.result.sha }}.
              <details><summary>see more</summary>

              Workflow log [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).

              </details>
              `
            })
