name: Publish Insider Build

on:
  # only run when a comment is created under a pr
  issue_comment:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    permissions:
      issues: write
      # allow writing comments on the PR
      contents: write
      pull-requests: write

    steps:
      - name: Start the comment
        id: start-comment
        uses: actions/github-script@v6
        with:
          # github-token: ${{ env.GITHUB_TOKEN }}
          script: |
            const result = await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              Publishing an insiders build. Will update this comment when done.
              <details><summary>see more</summary>

              Follow the workflow run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

              </details>
              `
            })

            console.log(result)

            const commentId = result.data.id

            const {data: pullRequest} = await github.rest.pulls.get({
              ...github.context.repo,
              pull_number: context.issue.number
            })

            console.log(pullRequest)

            return result

      # get pull request ref from ${{ github.event.issue.pull_request.url }}, and print it
      - name: Get pull request ref
        id: pr-ref
        # this gets the pull request ref from the issue_comment event. curl is used to get the pull request ref from the pull request url, and jq is used to parse the json response
        run: |
          PR_REF=$(curl -s ${{ github.event.issue.pull_request.url }} | jq -r .head.ref)
          echo "PR_REF=$PR_REF" >> $GITHUB_ENV
          echo "PR_REF=$PR_REF"

      - name: Check if user is AriaMinaei and comment contains "/Publish insiders build"
        if: "${{ github.event.comment.user.login }} == 'AriaMinaei' && contains(${{ github.event.comment.body }}, '/Publish insiders build')"
        run: |
          echo "User is AriaMinaei and comment contains the trigger."

      # checkout the repo at the branch that the PR is targeting
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.PR_REF }}

      - name: Get the latest commit hash
        id: last-commit
        run: |
          COMMIT=$(git log --pretty=format:'%h' -n 1)
          echo "Latest commit hash: $COMMIT"
          echo "last-commit=$COMMIT" >> $GITHUB_ENV

      # - name: Leave a comment on the PR
      #   uses: actions/github-script@v6
      #   with:
      #     # github-token: ${{ env.GITHUB_TOKEN }}
      #     script: |
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: 'Latest commit hash: ${{ env.last-commit }}'
      #       })
