name: Publish Insider Build

on:
  # only run when a comment is created under a pr
  issue_comment:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: print everything in the event
        run: |
          echo "${{ toJson(github.event) }}"

      # get pull request ref from ${{ github.event.issue.pull_request.url }}, and print it
      - name: Get pull request ref
        id: pr-ref
        # this gets the pull request ref from the issue_comment event. curl is used to get the pull request ref from the pull request url, and jq is used to parse the json response
        run: |
          PR_REF=$(curl -s ${{ github.event.issue.pull_request.url }} | jq -r .head.ref)
          echo "PR_REF=$PR_REF" >> $GITHUB_ENV
          echo "PR_REF=$PR_REF"

      - name: Check if user is AriaMinaei and comment contains "/Publish insiders build"
        if: "${{ github.event.comment.user.login }} == 'AriaMinaei' && contains(${{ github.event.comment.body }}, '/Publish insiders build')"
        run: |
          echo "User is AriaMinaei and comment contains the trigger."

      # checkout the repo at the branch that the PR is targeting
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.PR_REF }}

      - name: Get the latest commit hash
        id: last-commit
        run: |
          COMMIT=$(git log --pretty=format:'%h' -n 1)
          echo "Latest commit hash: $COMMIT"
          echo "last-commit=$COMMIT" >> $GITHUB_ENV

      # leave a comment on the PR with the commit hash
      - name: Leave a comment on the PR with the commit hash
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            The latest commit hash is ${{ env.last-commit }}.
